services:
  # apps
  resource-service:
    container_name: resource-service
    build: ./resource-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - '8001:8001'
    depends_on:
      - song-service
      - resource-service-db

  song-service:
    container_name: song-service
    build: ./song-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - '8002:8002'
    depends_on:
      - song-service-db

  # dbs
  resource-service-db:
    image: 'postgres:17-alpine'
    container_name: resource-service-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${RESOURCE_SERVICE_DB}
    volumes:
      - resource-service-db-volume:/var/lib/postgresql/data
      - ./resource-db:/docker-entrypoint-initdb.d/

  song-service-db:
    image: 'postgres:17-alpine'
    container_name: song-service-db
    ports:
      - '8433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${SONG_SERVICE_DB}
    volumes:
      - song-service-db-volume:/var/lib/postgresql/data
      - ./song-db:/docker-entrypoint-initdb.d/

volumes:
  resource-service-db-volume:
  song-service-db-volume: