server:
  port: 8002
  error:
    include-message: always

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: song-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      show-sql: true
  datasource:
    username: postgres
    password: postgres

