server:
  port: 8080
  error:
    include-message: always

song-service:
  url: http://localhost:8081

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: resource-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_service_db
    username: postgres
    password: postgres
